FROM node:16-slim AS build-stage

WORKDIR /src/angular
COPY packege*.json .
RUN npm ci

COPY . .
RUN npm run build

FROM caddy

COPY --from=build-stage /src/angular/dist/angular-app /app
COPY deploy/Caddyfile /etc/caddy/Caddyfile

